### ISSUE TITLE
Error on first build using Xcode 15.4

### ISSUE THREAD

**Issue by nigels0** [mipar52/google-examples-swift#2] opened 2024-08-10 14:01 UTC
Hi,

I'm getting this error after downloading and installing the Pods

SDK does not contain 'libarclite' at the path '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/libarclite_iphoneos.a'; try increasing the minimum deployment target

I've tried changing the deployment target (up to 17.5) and still getting the error.

**Comment by mipar52** [comment] 2024-08-13 07:21
Hi @nigels0!

I've managed to reproduce the same issue on my end. It looks like the issue is connected with the `GMOAuth2` Pod.
You need to click on Pods > open the General tab & find the `GMOAuth2` target > raise the minimum deployment from iOS 8.0.

Hope this helps! Let me know if you have any additional questions.

**Comment by nigels0** [comment] 2024-08-14 18:07
Thanks = I've done this and - apart from a .mp4 file asset missing, it is erroring now because of the fact some function calls are now out of date.

**Comment by mipar52** [comment] 2024-08-20 08:45
Hi @nigels0 

Thank you for the feedback, glad to hear you've managed to resolve the issue.
Yes, I agree there are a few outdated calls, and this will be fixed in the near future in the sample application.

Since the first problem has been resolved, can we close this issue?

**Closed as completed** 2024-08-20 08:49 UTC
